{
 "title": "ODE Metrics",
 "time": { "from": "now-3h", "to": "now" },
 "panels": [
  {
   "title": "ODE Message Counts",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum by(topic) (rate(kafka_produced_rsu_messages_total[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "MEC Deposit Publish Rate",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 14 },
   "targets": [
    {
     "expr": "mec_deposit_etx_mqtt_publish_rate",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "MQTT Deposit Latency",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "rate(mec_deposit_etx_mqtt_processing_seconds_sum[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Stale Message Count",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 41 },
   "targets": [
    {
     "expr": "rate(mec_deposit_etx_mqtt_stale_total[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}